default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: Genki0612
  host: localhost

development:
  <<: *default
  database: postgres_development
  template: template0

test:
  <<: *default
  database: postgres_test
  template: template0

production:
  <<: *default
  password: <%= ENV['POSTGRES_DATABASE_PASSWORD'] %>